env:
  global:
    - ANDROID_PACKAGE='sampleGroceries.apk'
    - ANDROID_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/binnacle/platforms/android/app/build/outputs/apk/debug/
    - IOS_PACKAGE='sampleGroceries.zip'
    - IOS_APP_NAME='sampleGroceries.app'
    - IOS_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/binnacle/platforms/ios/build/emulator

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      install: true
      script: cd binnacle && npm i && npm run tslint
    - stage: "Build"
      os: osx
      env: 
        - BuildiOS="12"
        - Xcode="10.0"
      osx_image: xcode10
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd binnacle && tns build ios --bundle --env.aot --env.uglify
        - cd $IOS_PACKAGE_FOLDER && zip -r $IOS_PACKAGE $IOS_APP_NAME
    - language: android
      env:
        - BuildAndroid="28"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8.9.1
      script:
        - cd binnacle && tns build android --bundle --env.aot --env.uglify --env.snapshot
    - stage: "UI Tests"
      env:
        - AndroidEmulator="23"
      language: node_js
      os: linux
      node_js: "8"
      script:
      #  - npm i -g appium@1.8.0
        - cd binnacle && npm i
        - cd binnacle && travis_retry npm run e2e -- --runType android23 --appPath $ANDROID_PACKAGE
    - os: linux
      env: 
        - iOS="11"
      language: node_js 
      node_js: "8"
      script: 
      #  - npm i -g appium@1.8.0
        - cd binnacle && npm i
        - cd binnacle && travis_wait travis_retry npm run e2e -- --runType sim.iPhone8 --appPath $IOS_PACKAGE
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - pip install six
    - echo no | npm install -g nativescript@next --ignore-scripts
    - tns usage-reporting disable
    - tns error-reporting disable